var blueCushionSprite = new Image();
		blueCushionSprite.src = "sprites/overworld/blueCushion.png"
		blueCushionSprite.height = 16
		blueCushionSprite.width = 16
var blueRug1Sprite = new Image();
		blueRug1Sprite.src = "sprites/overworld/blueRug1.png"
		blueRug1Sprite.height = 16
		blueRug1Sprite.width = 16
var blueRug2Sprite = new Image();
		blueRug2Sprite.src = "sprites/overworld/blueRug2.png"
		blueRug2Sprite.height = 16
		blueRug2Sprite.width = 16
var blueRug3Sprite = new Image();
		blueRug3Sprite.src = "sprites/overworld/blueRug3.png"
		blueRug3Sprite.height = 16
		blueRug3Sprite.width = 16
var blueRug4Sprite = new Image();
		blueRug4Sprite.src = "sprites/overworld/blueRug4.png"
		blueRug4Sprite.height = 16
		blueRug4Sprite.width = 16
var blueRug5Sprite = new Image();
		blueRug5Sprite.src = "sprites/overworld/blueRug5.png"
		blueRug5Sprite.height = 16
		blueRug5Sprite.width = 16
var blueRug6Sprite = new Image();
		blueRug6Sprite.src = "sprites/overworld/blueRug6.png"
		blueRug6Sprite.height = 16
		blueRug6Sprite.width = 16
var blueRug7Sprite = new Image();
		blueRug7Sprite.src = "sprites/overworld/blueRug7.png"
		blueRug7Sprite.height = 16
		blueRug7Sprite.width = 16
var blueRug8Sprite = new Image();
		blueRug8Sprite.src = "sprites/overworld/blueRug8.png"
		blueRug8Sprite.height = 16
		blueRug8Sprite.width = 16
var blueRug9Sprite = new Image();
		blueRug9Sprite.src = "sprites/overworld/blueRug9.png"
		blueRug9Sprite.height = 16
		blueRug9Sprite.width = 16
var blueStoolSprite = new Image();
		blueStoolSprite.src = "sprites/overworld/blueStool.png"
		blueStoolSprite.height = 16
		blueStoolSprite.width = 16
var bushSprite = new Image();
		bushSprite.src = "sprites/overworld/bush.png"
		bushSprite.height = 16
		bushSprite.width = 16
var curtain1Sprite = new Image();
		curtain1Sprite.src = "sprites/overworld/curtain1.png"
		curtain1Sprite.height = 16
		curtain1Sprite.width = 16
var curtain2Sprite = new Image();
		curtain2Sprite.src = "sprites/overworld/curtain2.png"
		curtain2Sprite.height = 16
		curtain2Sprite.width = 16
var curtain3Sprite = new Image();
		curtain3Sprite.src = "sprites/overworld/curtain3.png"
		curtain3Sprite.height = 16
		curtain3Sprite.width = 16
var curtain4Sprite = new Image();
		curtain4Sprite.src = "sprites/overworld/curtain4.png"
		curtain4Sprite.height = 16
		curtain4Sprite.width = 16
var devTileSpriteSprite = new Image();
		devTileSpriteSprite.src = "sprites/overworld/devTileSprite.png"
		devTileSpriteSprite.height = 16
		devTileSpriteSprite.width = 16
var finalFloorSprite = new Image();
		finalFloorSprite.src = "sprites/overworld/finalFloor.png"
		finalFloorSprite.height = 16
		finalFloorSprite.width = 16
var finalStairs0Sprite = new Image();
		finalStairs0Sprite.src = "sprites/overworld/finalStairs0.png"
		finalStairs0Sprite.height = 16
		finalStairs0Sprite.width = 16
var finalStairs1Sprite = new Image();
		finalStairs1Sprite.src = "sprites/overworld/finalStairs1.png"
		finalStairs1Sprite.height = 16
		finalStairs1Sprite.width = 16
var finalStairs10Sprite = new Image();
		finalStairs10Sprite.src = "sprites/overworld/finalStairs10.png"
		finalStairs10Sprite.height = 16
		finalStairs10Sprite.width = 16
var finalStairs11Sprite = new Image();
		finalStairs11Sprite.src = "sprites/overworld/finalStairs11.png"
		finalStairs11Sprite.height = 16
		finalStairs11Sprite.width = 16
var finalStairs12Sprite = new Image();
		finalStairs12Sprite.src = "sprites/overworld/finalStairs12.png"
		finalStairs12Sprite.height = 16
		finalStairs12Sprite.width = 16
var finalStairs13Sprite = new Image();
		finalStairs13Sprite.src = "sprites/overworld/finalStairs13.png"
		finalStairs13Sprite.height = 16
		finalStairs13Sprite.width = 16
var finalStairs14Sprite = new Image();
		finalStairs14Sprite.src = "sprites/overworld/finalStairs14.png"
		finalStairs14Sprite.height = 16
		finalStairs14Sprite.width = 16
var finalStairs15Sprite = new Image();
		finalStairs15Sprite.src = "sprites/overworld/finalStairs15.png"
		finalStairs15Sprite.height = 16
		finalStairs15Sprite.width = 16
var finalStairs16Sprite = new Image();
		finalStairs16Sprite.src = "sprites/overworld/finalStairs16.png"
		finalStairs16Sprite.height = 16
		finalStairs16Sprite.width = 16
var finalStairs17Sprite = new Image();
		finalStairs17Sprite.src = "sprites/overworld/finalStairs17.png"
		finalStairs17Sprite.height = 16
		finalStairs17Sprite.width = 16
var finalStairs18Sprite = new Image();
		finalStairs18Sprite.src = "sprites/overworld/finalStairs18.png"
		finalStairs18Sprite.height = 16
		finalStairs18Sprite.width = 16
var finalStairs19Sprite = new Image();
		finalStairs19Sprite.src = "sprites/overworld/finalStairs19.png"
		finalStairs19Sprite.height = 16
		finalStairs19Sprite.width = 16
var finalStairs2Sprite = new Image();
		finalStairs2Sprite.src = "sprites/overworld/finalStairs2.png"
		finalStairs2Sprite.height = 16
		finalStairs2Sprite.width = 16
var finalStairs20Sprite = new Image();
		finalStairs20Sprite.src = "sprites/overworld/finalStairs20.png"
		finalStairs20Sprite.height = 16
		finalStairs20Sprite.width = 16
var finalStairs21Sprite = new Image();
		finalStairs21Sprite.src = "sprites/overworld/finalStairs21.png"
		finalStairs21Sprite.height = 16
		finalStairs21Sprite.width = 16
var finalStairs22Sprite = new Image();
		finalStairs22Sprite.src = "sprites/overworld/finalStairs22.png"
		finalStairs22Sprite.height = 16
		finalStairs22Sprite.width = 16
var finalStairs23Sprite = new Image();
		finalStairs23Sprite.src = "sprites/overworld/finalStairs23.png"
		finalStairs23Sprite.height = 16
		finalStairs23Sprite.width = 16
var finalStairs24Sprite = new Image();
		finalStairs24Sprite.src = "sprites/overworld/finalStairs24.png"
		finalStairs24Sprite.height = 16
		finalStairs24Sprite.width = 16
var finalStairs25Sprite = new Image();
		finalStairs25Sprite.src = "sprites/overworld/finalStairs25.png"
		finalStairs25Sprite.height = 16
		finalStairs25Sprite.width = 16
var finalStairs26Sprite = new Image();
		finalStairs26Sprite.src = "sprites/overworld/finalStairs26.png"
		finalStairs26Sprite.height = 16
		finalStairs26Sprite.width = 16
var finalStairs27Sprite = new Image();
		finalStairs27Sprite.src = "sprites/overworld/finalStairs27.png"
		finalStairs27Sprite.height = 16
		finalStairs27Sprite.width = 16
var finalStairs28Sprite = new Image();
		finalStairs28Sprite.src = "sprites/overworld/finalStairs28.png"
		finalStairs28Sprite.height = 16
		finalStairs28Sprite.width = 16
var finalStairs29Sprite = new Image();
		finalStairs29Sprite.src = "sprites/overworld/finalStairs29.png"
		finalStairs29Sprite.height = 16
		finalStairs29Sprite.width = 16
var finalStairs3Sprite = new Image();
		finalStairs3Sprite.src = "sprites/overworld/finalStairs3.png"
		finalStairs3Sprite.height = 16
		finalStairs3Sprite.width = 16
var finalStairs4Sprite = new Image();
		finalStairs4Sprite.src = "sprites/overworld/finalStairs4.png"
		finalStairs4Sprite.height = 16
		finalStairs4Sprite.width = 16
var finalStairs5Sprite = new Image();
		finalStairs5Sprite.src = "sprites/overworld/finalStairs5.png"
		finalStairs5Sprite.height = 16
		finalStairs5Sprite.width = 16
var finalStairs6Sprite = new Image();
		finalStairs6Sprite.src = "sprites/overworld/finalStairs6.png"
		finalStairs6Sprite.height = 16
		finalStairs6Sprite.width = 16
var finalStairs7Sprite = new Image();
		finalStairs7Sprite.src = "sprites/overworld/finalStairs7.png"
		finalStairs7Sprite.height = 16
		finalStairs7Sprite.width = 16
var finalStairs8Sprite = new Image();
		finalStairs8Sprite.src = "sprites/overworld/finalStairs8.png"
		finalStairs8Sprite.height = 16
		finalStairs8Sprite.width = 16
var finalStairs9Sprite = new Image();
		finalStairs9Sprite.src = "sprites/overworld/finalStairs9.png"
		finalStairs9Sprite.height = 16
		finalStairs9Sprite.width = 16
var flowerSprite = new Image();
		flowerSprite.src = "sprites/overworld/flower.png"
		flowerSprite.height = 16
		flowerSprite.width = 16
var friendSprite = new Image();
		friendSprite.src = "sprites/overworld/friend.png"
		friendSprite.height = 16
		friendSprite.width = 16
var grassSprite = new Image();
		grassSprite.src = "sprites/overworld/grass.png"
		grassSprite.height = 16
		grassSprite.width = 16
var gym00Sprite = new Image();
		gym00Sprite.src = "sprites/overworld/gym00.png"
		gym00Sprite.height = 16
		gym00Sprite.width = 16
var gym01Sprite = new Image();
		gym01Sprite.src = "sprites/overworld/gym01.png"
		gym01Sprite.height = 16
		gym01Sprite.width = 16
var gym010Sprite = new Image();
		gym010Sprite.src = "sprites/overworld/gym010.png"
		gym010Sprite.height = 16
		gym010Sprite.width = 16
var gym011Sprite = new Image();
		gym011Sprite.src = "sprites/overworld/gym011.png"
		gym011Sprite.height = 16
		gym011Sprite.width = 16
var gym012Sprite = new Image();
		gym012Sprite.src = "sprites/overworld/gym012.png"
		gym012Sprite.height = 16
		gym012Sprite.width = 16
var gym013Sprite = new Image();
		gym013Sprite.src = "sprites/overworld/gym013.png"
		gym013Sprite.height = 16
		gym013Sprite.width = 16
var gym014Sprite = new Image();
		gym014Sprite.src = "sprites/overworld/gym014.png"
		gym014Sprite.height = 16
		gym014Sprite.width = 16
var gym015Sprite = new Image();
		gym015Sprite.src = "sprites/overworld/gym015.png"
		gym015Sprite.height = 16
		gym015Sprite.width = 16
var gym016Sprite = new Image();
		gym016Sprite.src = "sprites/overworld/gym016.png"
		gym016Sprite.height = 16
		gym016Sprite.width = 16
var gym017Sprite = new Image();
		gym017Sprite.src = "sprites/overworld/gym017.png"
		gym017Sprite.height = 16
		gym017Sprite.width = 16
var gym018Sprite = new Image();
		gym018Sprite.src = "sprites/overworld/gym018.png"
		gym018Sprite.height = 16
		gym018Sprite.width = 16
var gym019Sprite = new Image();
		gym019Sprite.src = "sprites/overworld/gym019.png"
		gym019Sprite.height = 16
		gym019Sprite.width = 16
var gym02Sprite = new Image();
		gym02Sprite.src = "sprites/overworld/gym02.png"
		gym02Sprite.height = 16
		gym02Sprite.width = 16
var gym020Sprite = new Image();
		gym020Sprite.src = "sprites/overworld/gym020.png"
		gym020Sprite.height = 16
		gym020Sprite.width = 16
var gym021Sprite = new Image();
		gym021Sprite.src = "sprites/overworld/gym021.png"
		gym021Sprite.height = 16
		gym021Sprite.width = 16
var gym022Sprite = new Image();
		gym022Sprite.src = "sprites/overworld/gym022.png"
		gym022Sprite.height = 16
		gym022Sprite.width = 16
var gym023Sprite = new Image();
		gym023Sprite.src = "sprites/overworld/gym023.png"
		gym023Sprite.height = 16
		gym023Sprite.width = 16
var gym024Sprite = new Image();
		gym024Sprite.src = "sprites/overworld/gym024.png"
		gym024Sprite.height = 16
		gym024Sprite.width = 16
var gym025Sprite = new Image();
		gym025Sprite.src = "sprites/overworld/gym025.png"
		gym025Sprite.height = 16
		gym025Sprite.width = 16
var gym026Sprite = new Image();
		gym026Sprite.src = "sprites/overworld/gym026.png"
		gym026Sprite.height = 16
		gym026Sprite.width = 16
var gym027Sprite = new Image();
		gym027Sprite.src = "sprites/overworld/gym027.png"
		gym027Sprite.height = 16
		gym027Sprite.width = 16
var gym028Sprite = new Image();
		gym028Sprite.src = "sprites/overworld/gym028.png"
		gym028Sprite.height = 16
		gym028Sprite.width = 16
var gym029Sprite = new Image();
		gym029Sprite.src = "sprites/overworld/gym029.png"
		gym029Sprite.height = 16
		gym029Sprite.width = 16
var gym03Sprite = new Image();
		gym03Sprite.src = "sprites/overworld/gym03.png"
		gym03Sprite.height = 16
		gym03Sprite.width = 16
var gym030Sprite = new Image();
		gym030Sprite.src = "sprites/overworld/gym030.png"
		gym030Sprite.height = 16
		gym030Sprite.width = 16
var gym031Sprite = new Image();
		gym031Sprite.src = "sprites/overworld/gym031.png"
		gym031Sprite.height = 16
		gym031Sprite.width = 16
var gym032Sprite = new Image();
		gym032Sprite.src = "sprites/overworld/gym032.png"
		gym032Sprite.height = 16
		gym032Sprite.width = 16
var gym033Sprite = new Image();
		gym033Sprite.src = "sprites/overworld/gym033.png"
		gym033Sprite.height = 16
		gym033Sprite.width = 16
var gym034Sprite = new Image();
		gym034Sprite.src = "sprites/overworld/gym034.png"
		gym034Sprite.height = 16
		gym034Sprite.width = 16
var gym035Sprite = new Image();
		gym035Sprite.src = "sprites/overworld/gym035.png"
		gym035Sprite.height = 16
		gym035Sprite.width = 16
var gym04Sprite = new Image();
		gym04Sprite.src = "sprites/overworld/gym04.png"
		gym04Sprite.height = 16
		gym04Sprite.width = 16
var gym05Sprite = new Image();
		gym05Sprite.src = "sprites/overworld/gym05.png"
		gym05Sprite.height = 16
		gym05Sprite.width = 16
var gym06Sprite = new Image();
		gym06Sprite.src = "sprites/overworld/gym06.png"
		gym06Sprite.height = 16
		gym06Sprite.width = 16
var gym07Sprite = new Image();
		gym07Sprite.src = "sprites/overworld/gym07.png"
		gym07Sprite.height = 16
		gym07Sprite.width = 16
var gym08Sprite = new Image();
		gym08Sprite.src = "sprites/overworld/gym08.png"
		gym08Sprite.height = 16
		gym08Sprite.width = 16
var gym09Sprite = new Image();
		gym09Sprite.src = "sprites/overworld/gym09.png"
		gym09Sprite.height = 16
		gym09Sprite.width = 16
var healer0Sprite = new Image();
		healer0Sprite.src = "sprites/overworld/healer0.png"
		healer0Sprite.height = 16
		healer0Sprite.width = 16
var healer1Sprite = new Image();
		healer1Sprite.src = "sprites/overworld/healer1.png"
		healer1Sprite.height = 16
		healer1Sprite.width = 16
var healer2Sprite = new Image();
		healer2Sprite.src = "sprites/overworld/healer2.png"
		healer2Sprite.height = 16
		healer2Sprite.width = 16
var healer3Sprite = new Image();
		healer3Sprite.src = "sprites/overworld/healer3.png"
		healer3Sprite.height = 16
		healer3Sprite.width = 16
var hospital0Sprite = new Image();
		hospital0Sprite.src = "sprites/overworld/hospital0.png"
		hospital0Sprite.height = 16
		hospital0Sprite.width = 16
var hospital1Sprite = new Image();
		hospital1Sprite.src = "sprites/overworld/hospital1.png"
		hospital1Sprite.height = 16
		hospital1Sprite.width = 16
var hospital10Sprite = new Image();
		hospital10Sprite.src = "sprites/overworld/hospital10.png"
		hospital10Sprite.height = 16
		hospital10Sprite.width = 16
var hospital11Sprite = new Image();
		hospital11Sprite.src = "sprites/overworld/hospital11.png"
		hospital11Sprite.height = 16
		hospital11Sprite.width = 16
var hospital12Sprite = new Image();
		hospital12Sprite.src = "sprites/overworld/hospital12.png"
		hospital12Sprite.height = 16
		hospital12Sprite.width = 16
var hospital13Sprite = new Image();
		hospital13Sprite.src = "sprites/overworld/hospital13.png"
		hospital13Sprite.height = 16
		hospital13Sprite.width = 16
var hospital14Sprite = new Image();
		hospital14Sprite.src = "sprites/overworld/hospital14.png"
		hospital14Sprite.height = 16
		hospital14Sprite.width = 16
var hospital15Sprite = new Image();
		hospital15Sprite.src = "sprites/overworld/hospital15.png"
		hospital15Sprite.height = 16
		hospital15Sprite.width = 16
var hospital16Sprite = new Image();
		hospital16Sprite.src = "sprites/overworld/hospital16.png"
		hospital16Sprite.height = 16
		hospital16Sprite.width = 16
var hospital17Sprite = new Image();
		hospital17Sprite.src = "sprites/overworld/hospital17.png"
		hospital17Sprite.height = 16
		hospital17Sprite.width = 16
var hospital18Sprite = new Image();
		hospital18Sprite.src = "sprites/overworld/hospital18.png"
		hospital18Sprite.height = 16
		hospital18Sprite.width = 16
var hospital19Sprite = new Image();
		hospital19Sprite.src = "sprites/overworld/hospital19.png"
		hospital19Sprite.height = 16
		hospital19Sprite.width = 16
var hospital2Sprite = new Image();
		hospital2Sprite.src = "sprites/overworld/hospital2.png"
		hospital2Sprite.height = 16
		hospital2Sprite.width = 16
var hospital20Sprite = new Image();
		hospital20Sprite.src = "sprites/overworld/hospital20.png"
		hospital20Sprite.height = 16
		hospital20Sprite.width = 16
var hospital21Sprite = new Image();
		hospital21Sprite.src = "sprites/overworld/hospital21.png"
		hospital21Sprite.height = 16
		hospital21Sprite.width = 16
var hospital22Sprite = new Image();
		hospital22Sprite.src = "sprites/overworld/hospital22.png"
		hospital22Sprite.height = 16
		hospital22Sprite.width = 16
var hospital23Sprite = new Image();
		hospital23Sprite.src = "sprites/overworld/hospital23.png"
		hospital23Sprite.height = 16
		hospital23Sprite.width = 16
var hospital24Sprite = new Image();
		hospital24Sprite.src = "sprites/overworld/hospital24.png"
		hospital24Sprite.height = 16
		hospital24Sprite.width = 16
var hospital25Sprite = new Image();
		hospital25Sprite.src = "sprites/overworld/hospital25.png"
		hospital25Sprite.height = 16
		hospital25Sprite.width = 16
var hospital26Sprite = new Image();
		hospital26Sprite.src = "sprites/overworld/hospital26.png"
		hospital26Sprite.height = 16
		hospital26Sprite.width = 16
var hospital27Sprite = new Image();
		hospital27Sprite.src = "sprites/overworld/hospital27.png"
		hospital27Sprite.height = 16
		hospital27Sprite.width = 16
var hospital28Sprite = new Image();
		hospital28Sprite.src = "sprites/overworld/hospital28.png"
		hospital28Sprite.height = 16
		hospital28Sprite.width = 16
var hospital29Sprite = new Image();
		hospital29Sprite.src = "sprites/overworld/hospital29.png"
		hospital29Sprite.height = 16
		hospital29Sprite.width = 16
var hospital3Sprite = new Image();
		hospital3Sprite.src = "sprites/overworld/hospital3.png"
		hospital3Sprite.height = 16
		hospital3Sprite.width = 16
var hospital4Sprite = new Image();
		hospital4Sprite.src = "sprites/overworld/hospital4.png"
		hospital4Sprite.height = 16
		hospital4Sprite.width = 16
var hospital5Sprite = new Image();
		hospital5Sprite.src = "sprites/overworld/hospital5.png"
		hospital5Sprite.height = 16
		hospital5Sprite.width = 16
var hospital6Sprite = new Image();
		hospital6Sprite.src = "sprites/overworld/hospital6.png"
		hospital6Sprite.height = 16
		hospital6Sprite.width = 16
var hospital7Sprite = new Image();
		hospital7Sprite.src = "sprites/overworld/hospital7.png"
		hospital7Sprite.height = 16
		hospital7Sprite.width = 16
var hospital8Sprite = new Image();
		hospital8Sprite.src = "sprites/overworld/hospital8.png"
		hospital8Sprite.height = 16
		hospital8Sprite.width = 16
var hospital9Sprite = new Image();
		hospital9Sprite.src = "sprites/overworld/hospital9.png"
		hospital9Sprite.height = 16
		hospital9Sprite.width = 16
var hospitalDesk0Sprite = new Image();
		hospitalDesk0Sprite.src = "sprites/overworld/hospitalDesk0.png"
		hospitalDesk0Sprite.height = 16
		hospitalDesk0Sprite.width = 16
var hospitalDesk1Sprite = new Image();
		hospitalDesk1Sprite.src = "sprites/overworld/hospitalDesk1.png"
		hospitalDesk1Sprite.height = 16
		hospitalDesk1Sprite.width = 16
var hospitalDesk10Sprite = new Image();
		hospitalDesk10Sprite.src = "sprites/overworld/hospitalDesk10.png"
		hospitalDesk10Sprite.height = 16
		hospitalDesk10Sprite.width = 16
var hospitalDesk11Sprite = new Image();
		hospitalDesk11Sprite.src = "sprites/overworld/hospitalDesk11.png"
		hospitalDesk11Sprite.height = 16
		hospitalDesk11Sprite.width = 16
var hospitalDesk2Sprite = new Image();
		hospitalDesk2Sprite.src = "sprites/overworld/hospitalDesk2.png"
		hospitalDesk2Sprite.height = 16
		hospitalDesk2Sprite.width = 16
var hospitalDesk3Sprite = new Image();
		hospitalDesk3Sprite.src = "sprites/overworld/hospitalDesk3.png"
		hospitalDesk3Sprite.height = 16
		hospitalDesk3Sprite.width = 16
var hospitalDesk4Sprite = new Image();
		hospitalDesk4Sprite.src = "sprites/overworld/hospitalDesk4.png"
		hospitalDesk4Sprite.height = 16
		hospitalDesk4Sprite.width = 16
var hospitalDesk5Sprite = new Image();
		hospitalDesk5Sprite.src = "sprites/overworld/hospitalDesk5.png"
		hospitalDesk5Sprite.height = 16
		hospitalDesk5Sprite.width = 16
var hospitalDesk6Sprite = new Image();
		hospitalDesk6Sprite.src = "sprites/overworld/hospitalDesk6.png"
		hospitalDesk6Sprite.height = 16
		hospitalDesk6Sprite.width = 16
var hospitalDesk7Sprite = new Image();
		hospitalDesk7Sprite.src = "sprites/overworld/hospitalDesk7.png"
		hospitalDesk7Sprite.height = 16
		hospitalDesk7Sprite.width = 16
var hospitalDesk8Sprite = new Image();
		hospitalDesk8Sprite.src = "sprites/overworld/hospitalDesk8.png"
		hospitalDesk8Sprite.height = 16
		hospitalDesk8Sprite.width = 16
var hospitalDesk9Sprite = new Image();
		hospitalDesk9Sprite.src = "sprites/overworld/hospitalDesk9.png"
		hospitalDesk9Sprite.height = 16
		hospitalDesk9Sprite.width = 16
var house00Sprite = new Image();
		house00Sprite.src = "sprites/overworld/house00.png"
		house00Sprite.height = 16
		house00Sprite.width = 16
var house01Sprite = new Image();
		house01Sprite.src = "sprites/overworld/house01.png"
		house01Sprite.height = 16
		house01Sprite.width = 16
var house010Sprite = new Image();
		house010Sprite.src = "sprites/overworld/house010.png"
		house010Sprite.height = 16
		house010Sprite.width = 16
var house011Sprite = new Image();
		house011Sprite.src = "sprites/overworld/house011.png"
		house011Sprite.height = 16
		house011Sprite.width = 16
var house012Sprite = new Image();
		house012Sprite.src = "sprites/overworld/house012.png"
		house012Sprite.height = 16
		house012Sprite.width = 16
var house013Sprite = new Image();
		house013Sprite.src = "sprites/overworld/house013.png"
		house013Sprite.height = 16
		house013Sprite.width = 16
var house014Sprite = new Image();
		house014Sprite.src = "sprites/overworld/house014.png"
		house014Sprite.height = 16
		house014Sprite.width = 16
var house015Sprite = new Image();
		house015Sprite.src = "sprites/overworld/house015.png"
		house015Sprite.height = 16
		house015Sprite.width = 16
var house016Sprite = new Image();
		house016Sprite.src = "sprites/overworld/house016.png"
		house016Sprite.height = 16
		house016Sprite.width = 16
var house017Sprite = new Image();
		house017Sprite.src = "sprites/overworld/house017.png"
		house017Sprite.height = 16
		house017Sprite.width = 16
var house018Sprite = new Image();
		house018Sprite.src = "sprites/overworld/house018.png"
		house018Sprite.height = 16
		house018Sprite.width = 16
var house019Sprite = new Image();
		house019Sprite.src = "sprites/overworld/house019.png"
		house019Sprite.height = 16
		house019Sprite.width = 16
var house02Sprite = new Image();
		house02Sprite.src = "sprites/overworld/house02.png"
		house02Sprite.height = 16
		house02Sprite.width = 16
var house020Sprite = new Image();
		house020Sprite.src = "sprites/overworld/house020.png"
		house020Sprite.height = 16
		house020Sprite.width = 16
var house021Sprite = new Image();
		house021Sprite.src = "sprites/overworld/house021.png"
		house021Sprite.height = 16
		house021Sprite.width = 16
var house022Sprite = new Image();
		house022Sprite.src = "sprites/overworld/house022.png"
		house022Sprite.height = 16
		house022Sprite.width = 16
var house023Sprite = new Image();
		house023Sprite.src = "sprites/overworld/house023.png"
		house023Sprite.height = 16
		house023Sprite.width = 16
var house024Sprite = new Image();
		house024Sprite.src = "sprites/overworld/house024.png"
		house024Sprite.height = 16
		house024Sprite.width = 16
var house03Sprite = new Image();
		house03Sprite.src = "sprites/overworld/house03.png"
		house03Sprite.height = 16
		house03Sprite.width = 16
var house04Sprite = new Image();
		house04Sprite.src = "sprites/overworld/house04.png"
		house04Sprite.height = 16
		house04Sprite.width = 16
var house05Sprite = new Image();
		house05Sprite.src = "sprites/overworld/house05.png"
		house05Sprite.height = 16
		house05Sprite.width = 16
var house06Sprite = new Image();
		house06Sprite.src = "sprites/overworld/house06.png"
		house06Sprite.height = 16
		house06Sprite.width = 16
var house07Sprite = new Image();
		house07Sprite.src = "sprites/overworld/house07.png"
		house07Sprite.height = 16
		house07Sprite.width = 16
var house08Sprite = new Image();
		house08Sprite.src = "sprites/overworld/house08.png"
		house08Sprite.height = 16
		house08Sprite.width = 16
var house09Sprite = new Image();
		house09Sprite.src = "sprites/overworld/house09.png"
		house09Sprite.height = 16
		house09Sprite.width = 16
var lampBottomLeftSprite = new Image();
		lampBottomLeftSprite.src = "sprites/overworld/lampBottomLeft.png"
		lampBottomLeftSprite.height = 16
		lampBottomLeftSprite.width = 16
var lampBottomRightSprite = new Image();
		lampBottomRightSprite.src = "sprites/overworld/lampBottomRight.png"
		lampBottomRightSprite.height = 16
		lampBottomRightSprite.width = 16
var lampMiddleLeftSprite = new Image();
		lampMiddleLeftSprite.src = "sprites/overworld/lampMiddleLeft.png"
		lampMiddleLeftSprite.height = 16
		lampMiddleLeftSprite.width = 16
var lampMiddleRightSprite = new Image();
		lampMiddleRightSprite.src = "sprites/overworld/lampMiddleRight.png"
		lampMiddleRightSprite.height = 16
		lampMiddleRightSprite.width = 16
var lampTopLeftSprite = new Image();
		lampTopLeftSprite.src = "sprites/overworld/lampTopLeft.png"
		lampTopLeftSprite.height = 16
		lampTopLeftSprite.width = 16
var lampTopRightSprite = new Image();
		lampTopRightSprite.src = "sprites/overworld/lampTopRight.png"
		lampTopRightSprite.height = 16
		lampTopRightSprite.width = 16
var longGrassSprite = new Image();
		longGrassSprite.src = "sprites/overworld/longGrass.png"
		longGrassSprite.height = 16
		longGrassSprite.width = 16
var longGrass2Sprite = new Image();
		longGrass2Sprite.src = "sprites/overworld/longGrass2.png"
		longGrass2Sprite.height = 16
		longGrass2Sprite.width = 16
var longGrass3Sprite = new Image();
		longGrass3Sprite.src = "sprites/overworld/longGrass3.png"
		longGrass3Sprite.height = 16
		longGrass3Sprite.width = 16
var npcSprite = new Image();
		npcSprite.src = "sprites/overworld/npc.png"
		npcSprite.height = 16
		npcSprite.width = 16
var nurseSprite = new Image();
		nurseSprite.src = "sprites/overworld/nurse.png"
		nurseSprite.height = 16
		nurseSprite.width = 16
var path0BottomLeftSprite = new Image();
		path0BottomLeftSprite.src = "sprites/overworld/path0BottomLeft.png"
		path0BottomLeftSprite.height = 16
		path0BottomLeftSprite.width = 16
var path0BottomMiddleSprite = new Image();
		path0BottomMiddleSprite.src = "sprites/overworld/path0BottomMiddle.png"
		path0BottomMiddleSprite.height = 16
		path0BottomMiddleSprite.width = 16
var path0BottomRightSprite = new Image();
		path0BottomRightSprite.src = "sprites/overworld/path0BottomRight.png"
		path0BottomRightSprite.height = 16
		path0BottomRightSprite.width = 16
var path0LeftDownSprite = new Image();
		path0LeftDownSprite.src = "sprites/overworld/path0LeftDown.png"
		path0LeftDownSprite.height = 16
		path0LeftDownSprite.width = 16
var path0LeftUpSprite = new Image();
		path0LeftUpSprite.src = "sprites/overworld/path0LeftUp.png"
		path0LeftUpSprite.height = 16
		path0LeftUpSprite.width = 16
var path0MiddleSprite = new Image();
		path0MiddleSprite.src = "sprites/overworld/path0Middle.png"
		path0MiddleSprite.height = 16
		path0MiddleSprite.width = 16
var path0MiddleLeftSprite = new Image();
		path0MiddleLeftSprite.src = "sprites/overworld/path0MiddleLeft.png"
		path0MiddleLeftSprite.height = 16
		path0MiddleLeftSprite.width = 16
var path0MiddleRightSprite = new Image();
		path0MiddleRightSprite.src = "sprites/overworld/path0MiddleRight.png"
		path0MiddleRightSprite.height = 16
		path0MiddleRightSprite.width = 16
var path0RightDownSprite = new Image();
		path0RightDownSprite.src = "sprites/overworld/path0RightDown.png"
		path0RightDownSprite.height = 16
		path0RightDownSprite.width = 16
var path0RightUpSprite = new Image();
		path0RightUpSprite.src = "sprites/overworld/path0RightUp.png"
		path0RightUpSprite.height = 16
		path0RightUpSprite.width = 16
var path0TopLeftSprite = new Image();
		path0TopLeftSprite.src = "sprites/overworld/path0TopLeft.png"
		path0TopLeftSprite.height = 16
		path0TopLeftSprite.width = 16
var path0TopMiddleSprite = new Image();
		path0TopMiddleSprite.src = "sprites/overworld/path0TopMiddle.png"
		path0TopMiddleSprite.height = 16
		path0TopMiddleSprite.width = 16
var path0TopRightSprite = new Image();
		path0TopRightSprite.src = "sprites/overworld/path0TopRight.png"
		path0TopRightSprite.height = 16
		path0TopRightSprite.width = 16
var playerSprite = new Image();
		playerSprite.src = "sprites/overworld/player.png"
		playerSprite.height = 16
		playerSprite.width = 16
var potPlant0Sprite = new Image();
		potPlant0Sprite.src = "sprites/overworld/potPlant0.png"
		potPlant0Sprite.height = 16
		potPlant0Sprite.width = 16
var potPlant1Sprite = new Image();
		potPlant1Sprite.src = "sprites/overworld/potPlant1.png"
		potPlant1Sprite.height = 16
		potPlant1Sprite.width = 16
var redRug1Sprite = new Image();
		redRug1Sprite.src = "sprites/overworld/redRug1.png"
		redRug1Sprite.height = 16
		redRug1Sprite.width = 16
var redRug2Sprite = new Image();
		redRug2Sprite.src = "sprites/overworld/redRug2.png"
		redRug2Sprite.height = 16
		redRug2Sprite.width = 16
var rockBottomLeftSprite = new Image();
		rockBottomLeftSprite.src = "sprites/overworld/rockBottomLeft.png"
		rockBottomLeftSprite.height = 16
		rockBottomLeftSprite.width = 16
var rockBottomMiddleSprite = new Image();
		rockBottomMiddleSprite.src = "sprites/overworld/rockBottomMiddle.png"
		rockBottomMiddleSprite.height = 16
		rockBottomMiddleSprite.width = 16
var rockBottomRightSprite = new Image();
		rockBottomRightSprite.src = "sprites/overworld/rockBottomRight.png"
		rockBottomRightSprite.height = 16
		rockBottomRightSprite.width = 16
var rockInsideTopLeftSprite = new Image();
		rockInsideTopLeftSprite.src = "sprites/overworld/rockInsideTopLeft.png"
		rockInsideTopLeftSprite.height = 16
		rockInsideTopLeftSprite.width = 16
var rockInsideTopRightSprite = new Image();
		rockInsideTopRightSprite.src = "sprites/overworld/rockInsideTopRight.png"
		rockInsideTopRightSprite.height = 16
		rockInsideTopRightSprite.width = 16
var rockMiddleSprite = new Image();
		rockMiddleSprite.src = "sprites/overworld/rockMiddle.png"
		rockMiddleSprite.height = 16
		rockMiddleSprite.width = 16
var rockMiddleLeftSprite = new Image();
		rockMiddleLeftSprite.src = "sprites/overworld/rockMiddleLeft.png"
		rockMiddleLeftSprite.height = 16
		rockMiddleLeftSprite.width = 16
var rockMiddleRightSprite = new Image();
		rockMiddleRightSprite.src = "sprites/overworld/rockMiddleRight.png"
		rockMiddleRightSprite.height = 16
		rockMiddleRightSprite.width = 16
var rockStairsSprite = new Image();
		rockStairsSprite.src = "sprites/overworld/rockStairs.png"
		rockStairsSprite.height = 16
		rockStairsSprite.width = 16
var rockTopLeftSprite = new Image();
		rockTopLeftSprite.src = "sprites/overworld/rockTopLeft.png"
		rockTopLeftSprite.height = 16
		rockTopLeftSprite.width = 16
var rockTopMiddleSprite = new Image();
		rockTopMiddleSprite.src = "sprites/overworld/rockTopMiddle.png"
		rockTopMiddleSprite.height = 16
		rockTopMiddleSprite.width = 16
var rockTopRightSprite = new Image();
		rockTopRightSprite.src = "sprites/overworld/rockTopRight.png"
		rockTopRightSprite.height = 16
		rockTopRightSprite.width = 16
var shop0Sprite = new Image();
		shop0Sprite.src = "sprites/overworld/shop0.png"
		shop0Sprite.height = 16
		shop0Sprite.width = 16
var shop1Sprite = new Image();
		shop1Sprite.src = "sprites/overworld/shop1.png"
		shop1Sprite.height = 16
		shop1Sprite.width = 16
var shop10Sprite = new Image();
		shop10Sprite.src = "sprites/overworld/shop10.png"
		shop10Sprite.height = 16
		shop10Sprite.width = 16
var shop11Sprite = new Image();
		shop11Sprite.src = "sprites/overworld/shop11.png"
		shop11Sprite.height = 16
		shop11Sprite.width = 16
var shop12Sprite = new Image();
		shop12Sprite.src = "sprites/overworld/shop12.png"
		shop12Sprite.height = 16
		shop12Sprite.width = 16
var shop13Sprite = new Image();
		shop13Sprite.src = "sprites/overworld/shop13.png"
		shop13Sprite.height = 16
		shop13Sprite.width = 16
var shop14Sprite = new Image();
		shop14Sprite.src = "sprites/overworld/shop14.png"
		shop14Sprite.height = 16
		shop14Sprite.width = 16
var shop15Sprite = new Image();
		shop15Sprite.src = "sprites/overworld/shop15.png"
		shop15Sprite.height = 16
		shop15Sprite.width = 16
var shop16Sprite = new Image();
		shop16Sprite.src = "sprites/overworld/shop16.png"
		shop16Sprite.height = 16
		shop16Sprite.width = 16
var shop17Sprite = new Image();
		shop17Sprite.src = "sprites/overworld/shop17.png"
		shop17Sprite.height = 16
		shop17Sprite.width = 16
var shop18Sprite = new Image();
		shop18Sprite.src = "sprites/overworld/shop18.png"
		shop18Sprite.height = 16
		shop18Sprite.width = 16
var shop19Sprite = new Image();
		shop19Sprite.src = "sprites/overworld/shop19.png"
		shop19Sprite.height = 16
		shop19Sprite.width = 16
var shop2Sprite = new Image();
		shop2Sprite.src = "sprites/overworld/shop2.png"
		shop2Sprite.height = 16
		shop2Sprite.width = 16
var shop20Sprite = new Image();
		shop20Sprite.src = "sprites/overworld/shop20.png"
		shop20Sprite.height = 16
		shop20Sprite.width = 16
var shop21Sprite = new Image();
		shop21Sprite.src = "sprites/overworld/shop21.png"
		shop21Sprite.height = 16
		shop21Sprite.width = 16
var shop22Sprite = new Image();
		shop22Sprite.src = "sprites/overworld/shop22.png"
		shop22Sprite.height = 16
		shop22Sprite.width = 16
var shop23Sprite = new Image();
		shop23Sprite.src = "sprites/overworld/shop23.png"
		shop23Sprite.height = 16
		shop23Sprite.width = 16
var shop24Sprite = new Image();
		shop24Sprite.src = "sprites/overworld/shop24.png"
		shop24Sprite.height = 16
		shop24Sprite.width = 16
var shop3Sprite = new Image();
		shop3Sprite.src = "sprites/overworld/shop3.png"
		shop3Sprite.height = 16
		shop3Sprite.width = 16
var shop4Sprite = new Image();
		shop4Sprite.src = "sprites/overworld/shop4.png"
		shop4Sprite.height = 16
		shop4Sprite.width = 16
var shop5Sprite = new Image();
		shop5Sprite.src = "sprites/overworld/shop5.png"
		shop5Sprite.height = 16
		shop5Sprite.width = 16
var shop6Sprite = new Image();
		shop6Sprite.src = "sprites/overworld/shop6.png"
		shop6Sprite.height = 16
		shop6Sprite.width = 16
var shop7Sprite = new Image();
		shop7Sprite.src = "sprites/overworld/shop7.png"
		shop7Sprite.height = 16
		shop7Sprite.width = 16
var shop8Sprite = new Image();
		shop8Sprite.src = "sprites/overworld/shop8.png"
		shop8Sprite.height = 16
		shop8Sprite.width = 16
var shop9Sprite = new Image();
		shop9Sprite.src = "sprites/overworld/shop9.png"
		shop9Sprite.height = 16
		shop9Sprite.width = 16
var statue0Sprite = new Image();
		statue0Sprite.src = "sprites/overworld/statue0.png"
		statue0Sprite.height = 16
		statue0Sprite.width = 16
var statue1Sprite = new Image();
		statue1Sprite.src = "sprites/overworld/statue1.png"
		statue1Sprite.height = 16
		statue1Sprite.width = 16
var ThumbSprite = new Image();
		ThumbSprite.src = "sprites/overworld/Thumbs.db"
		ThumbSprite.height = 16
		ThumbSprite.width = 16
var treeBottomSprite = new Image();
		treeBottomSprite.src = "sprites/overworld/treeBottom.png"
		treeBottomSprite.height = 16
		treeBottomSprite.width = 16
var treeMiddleSprite = new Image();
		treeMiddleSprite.src = "sprites/overworld/treeMiddle.png"
		treeMiddleSprite.height = 16
		treeMiddleSprite.width = 16
var treeTopSprite = new Image();
		treeTopSprite.src = "sprites/overworld/treeTop.png"
		treeTopSprite.height = 16
		treeTopSprite.width = 16
var triggerMatSprite = new Image();
		triggerMatSprite.src = "sprites/overworld/triggerMat.png"
		triggerMatSprite.height = 16
		triggerMatSprite.width = 16
var tv1Sprite = new Image();
		tv1Sprite.src = "sprites/overworld/tv1.png"
		tv1Sprite.height = 16
		tv1Sprite.width = 16
var tv2Sprite = new Image();
		tv2Sprite.src = "sprites/overworld/tv2.png"
		tv2Sprite.height = 16
		tv2Sprite.width = 16
var tv3Sprite = new Image();
		tv3Sprite.src = "sprites/overworld/tv3.png"
		tv3Sprite.height = 16
		tv3Sprite.width = 16
var tv4Sprite = new Image();
		tv4Sprite.src = "sprites/overworld/tv4.png"
		tv4Sprite.height = 16
		tv4Sprite.width = 16
var waterSprite = new Image();
		waterSprite.src = "sprites/overworld/water.png"
		waterSprite.height = 16
		waterSprite.width = 16
var waterBottomLeftSprite = new Image();
		waterBottomLeftSprite.src = "sprites/overworld/waterBottomLeft.png"
		waterBottomLeftSprite.height = 16
		waterBottomLeftSprite.width = 16
var waterBottomMiddleSprite = new Image();
		waterBottomMiddleSprite.src = "sprites/overworld/waterBottomMiddle.png"
		waterBottomMiddleSprite.height = 16
		waterBottomMiddleSprite.width = 16
var waterBottomRightSprite = new Image();
		waterBottomRightSprite.src = "sprites/overworld/waterBottomRight.png"
		waterBottomRightSprite.height = 16
		waterBottomRightSprite.width = 16
var waterMiddleLeftSprite = new Image();
		waterMiddleLeftSprite.src = "sprites/overworld/waterMiddleLeft.png"
		waterMiddleLeftSprite.height = 16
		waterMiddleLeftSprite.width = 16
var waterMiddleRightSprite = new Image();
		waterMiddleRightSprite.src = "sprites/overworld/waterMiddleRight.png"
		waterMiddleRightSprite.height = 16
		waterMiddleRightSprite.width = 16
var waterTopSprite = new Image();
		waterTopSprite.src = "sprites/overworld/waterTop.png"
		waterTopSprite.height = 16
		waterTopSprite.width = 16
var waterTopLeftSprite = new Image();
		waterTopLeftSprite.src = "sprites/overworld/waterTopLeft.png"
		waterTopLeftSprite.height = 16
		waterTopLeftSprite.width = 16
var waterTopRightSprite = new Image();
		waterTopRightSprite.src = "sprites/overworld/waterTopRight.png"
		waterTopRightSprite.height = 16
		waterTopRightSprite.width = 16
var woodFenceBottomLeftSprite = new Image();
		woodFenceBottomLeftSprite.src = "sprites/overworld/woodFenceBottomLeft.png"
		woodFenceBottomLeftSprite.height = 16
		woodFenceBottomLeftSprite.width = 16
var woodFenceBottomRightSprite = new Image();
		woodFenceBottomRightSprite.src = "sprites/overworld/woodFenceBottomRight.png"
		woodFenceBottomRightSprite.height = 16
		woodFenceBottomRightSprite.width = 16
var woodFenceMiddleLeftSprite = new Image();
		woodFenceMiddleLeftSprite.src = "sprites/overworld/woodFenceMiddleLeft.png"
		woodFenceMiddleLeftSprite.height = 16
		woodFenceMiddleLeftSprite.width = 16
var woodFenceMiddleRightSprite = new Image();
		woodFenceMiddleRightSprite.src = "sprites/overworld/woodFenceMiddleRight.png"
		woodFenceMiddleRightSprite.height = 16
		woodFenceMiddleRightSprite.width = 16
var woodFenceTopSprite = new Image();
		woodFenceTopSprite.src = "sprites/overworld/woodFenceTop.png"
		woodFenceTopSprite.height = 16
		woodFenceTopSprite.width = 16
var woodFenceTopLeftSprite = new Image();
		woodFenceTopLeftSprite.src = "sprites/overworld/woodFenceTopLeft.png"
		woodFenceTopLeftSprite.height = 16
		woodFenceTopLeftSprite.width = 16
var woodFenceTopRightSprite = new Image();
		woodFenceTopRightSprite.src = "sprites/overworld/woodFenceTopRight.png"
		woodFenceTopRightSprite.height = 16
		woodFenceTopRightSprite.width = 16
var woodFloorSprite = new Image();
		woodFloorSprite.src = "sprites/overworld/woodFloor.png"
		woodFloorSprite.height = 16
		woodFloorSprite.width = 16
var woodTable1Sprite = new Image();
		woodTable1Sprite.src = "sprites/overworld/woodTable1.png"
		woodTable1Sprite.height = 16
		woodTable1Sprite.width = 16
var woodTable2Sprite = new Image();
		woodTable2Sprite.src = "sprites/overworld/woodTable2.png"
		woodTable2Sprite.height = 16
		woodTable2Sprite.width = 16
var woodTable3Sprite = new Image();
		woodTable3Sprite.src = "sprites/overworld/woodTable3.png"
		woodTable3Sprite.height = 16
		woodTable3Sprite.width = 16
var woodTable4Sprite = new Image();
		woodTable4Sprite.src = "sprites/overworld/woodTable4.png"
		woodTable4Sprite.height = 16
		woodTable4Sprite.width = 16
var woodTable5Sprite = new Image();
		woodTable5Sprite.src = "sprites/overworld/woodTable5.png"
		woodTable5Sprite.height = 16
		woodTable5Sprite.width = 16
var woodTable6Sprite = new Image();
		woodTable6Sprite.src = "sprites/overworld/woodTable6.png"
		woodTable6Sprite.height = 16
		woodTable6Sprite.width = 16
var woodWallBottomLeftSprite = new Image();
		woodWallBottomLeftSprite.src = "sprites/overworld/woodWallBottomLeft.png"
		woodWallBottomLeftSprite.height = 16
		woodWallBottomLeftSprite.width = 16
var woodWallBottomMiddleSprite = new Image();
		woodWallBottomMiddleSprite.src = "sprites/overworld/woodWallBottomMiddle.png"
		woodWallBottomMiddleSprite.height = 16
		woodWallBottomMiddleSprite.width = 16
var woodWallBottomRightSprite = new Image();
		woodWallBottomRightSprite.src = "sprites/overworld/woodWallBottomRight.png"
		woodWallBottomRightSprite.height = 16
		woodWallBottomRightSprite.width = 16
var woodWallTopLeftSprite = new Image();
		woodWallTopLeftSprite.src = "sprites/overworld/woodWallTopLeft.png"
		woodWallTopLeftSprite.height = 16
		woodWallTopLeftSprite.width = 16
var woodWallTopMiddleSprite = new Image();
		woodWallTopMiddleSprite.src = "sprites/overworld/woodWallTopMiddle.png"
		woodWallTopMiddleSprite.height = 16
		woodWallTopMiddleSprite.width = 16
var woodWallTopRightSprite = new Image();
		woodWallTopRightSprite.src = "sprites/overworld/woodWallTopRight.png"
		woodWallTopRightSprite.height = 16
		woodWallTopRightSprite.width = 16
